########################################

# Define scoring mesh
/score/create/boxMesh dosimeterMesh
/score/mesh/boxSize 2000. 2000. 4000. mm
/score/mesh/nBin 20 20 40

# Filters
/score/quantity/doseDeposit doseDepGamma
/score/filter/particle gammaFilter gamma
/score/quantity/doseDeposit doseDepNeutron
/score/filter/particle neutronFilter neutron
/score/close
/score/list

########################################

# Run control
# /vis/disable
# /control/verbose 2
# /run/verbose 2
/run/beamOn 10000000
# /vis/enable

########################################

# Drawing projections
# /score/drawProjection dosimeterMesh doseDep

########################################
# Dump scorers to a file
/score/dumpQuantityToFile dosimeterMesh doseDepGamma doseDepGamma.csv
/score/dumpQuantityToFile dosimeterMesh doseDepNeutron doseDepNeutron.csv
