########################################
# LUNCH AREA DOSIMETER                 #
########################################
/score/create/boxMesh lunchAreaMesh
/score/mesh/boxSize 2000. 2000. 4000. mm
/score/mesh/translate/xyz 0. 0. 0. cm
/score/mesh/nBin 20 20 40
/score/quantity/doseDeposit doseDepAll
/score/quantity/nOfTrack nOfTrackAll
/score/quantity/nOfTrack nOfTrackGamma
/score/filter/particle gammaFilter gamma
/score/quantity/nOfTrack nOfTrackNeutron
/score/filter/particle neutronFilter neutron

########################################
# PARKING AREA DOSIMETER               #
########################################
/score/create/boxMesh parkingAreaMesh
/score/mesh/boxSize 2000. 2000. 4000. mm
/score/mesh/translate/xyz 0. 0. 0. cm
/score/mesh/nBin 20 20 40
/score/quantity/doseDeposit doseDepAll
/score/quantity/nOfTrack nOfTrackAll
/score/quantity/nOfTrack nOfTrackGamma
/score/filter/particle gammaFilter gamma
/score/quantity/nOfTrack nOfTrackNeutron
/score/filter/particle neutronFilter neutron




########################################
/score/close
/score/list

# Run control
# /vis/disable
# /control/verbose 2
# /run/verbose 2
/run/beamOn 10000
# /vis/enable

########################################

# Drawing projections
# /score/drawProjection dosimeterMesh doseDepAll

########################################
# Dump scorers to a file
/score/dumpQuantityToFile dosimeterMesh doseDepAll  doseDepAll.csv
/score/dumpQuantityToFile dosimeterMesh nOfTrackAll  nOfTrackAll.csv
/score/dumpQuantityToFile dosimeterMesh nOfTrackGamma  nOfTrackGamma.csv
/score/dumpQuantityToFile dosimeterMesh nOfTrackNeutron  nOfTrackNeutron.csv
/score/dumpQuantityToFile dosimeterMesh nOfTrackNeutrino  nOfTrackNeutrino.csv
/score/dumpQuantityToFile dosimeterMesh nOfTrackAntiNeutrino  nOfTrackAntiNeutrino.csv
