/run/initialize
/vis/open
/vis/scene/create
/vis/drawVolume
/vis/viewer/set/autoRefresh true
/vis/scene/add/trajectories smooth
/vis/scene/add/scale 1 m
/vis/scene/add/axes
/vis/scene/endOfEventAction accumulate -1

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set e+ red
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow
/vis/modeling/trajectories/drawByParticleID-0/set mu+ blue
/vis/modeling/trajectories/drawByParticleID-0/set mu- blue
/vis/modeling/trajectories/drawByParticleID-0/set pi+ white
/vis/modeling/trajectories/drawByParticleID-0/set pi- white
/vis/modeling/trajectories/drawByParticleID-0/set pi0 white
