# Open a viewer
/vis/open

# Draw scene
/vis/scene/create
/vis/drawVolume

# Set viewpoint
/vis/viewer/set/autoRefresh true
/vis/viewer/set/viewpointVector 1 0 0
/vis/viewer/set/upVector 0 0 1

# Drawing the tracks
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate -1

# Draw markers
/vis/scene/add/scale 1 m
/vis/scene/add/axes

# Set colors for particle identification
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set e+ red
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow
/vis/modeling/trajectories/drawByParticleID-0/set mu+ blue
/vis/modeling/trajectories/drawByParticleID-0/set mu- blue
/vis/modeling/trajectories/drawByParticleID-0/set pi+ white
/vis/modeling/trajectories/drawByParticleID-0/set pi- white
/vis/modeling/trajectories/drawByParticleID-0/set pi0 white
